const PREFIX = 'CALCULATOR__'

export const CalculatorActionTypes = {
  FETCH_CURRENCIES: `${PREFIX}FETCH_CURRENCIES`,
  FETCH_CURRENCIES_LOADING: `${PREFIX}FETCH_CURRENCIES_LOADING`,
  FETCH_CURRENCIES_SUCCESS: `${PREFIX}FETCH_CURRENCIES_SUCCESS`,
  FETCH_CURRENCIES_FAILURE: `${PREFIX}FETCH_CURRENCIES_FAILURE`,
  FETCH_CONVERSION: `${PREFIX}FETCH_CONVERSION_SUBSCRIPTIONS`,
  FETCH_CONVERSION_LOADING: `${PREFIX}FETCH_CONVERSION_LOADING`,
  FETCH_CONVERSION_SUCCESS: `${PREFIX}FETCH_CONVERSION_SUCCESS`,
  FETCH_CONVERSION_FAILURE: `${PREFIX}FETCH_CONVERSION_FAILURE`,
  RESET: `${PREFIX}RESET`,
}